name: "deploy-lock"
description: "Lock Action to support deployment locking for the branch-deploy Action"
author: "Grant Birkinbine"
branding:
  icon: 'lock'
  color: 'gray-dark'
inputs:
  github_token:
    description: The GitHub token used to create an authenticated client - Provided for you by default!
    default: ${{ github.token }}
    required: true
  lock_trigger:
    description: 'The string to look for in comments as an IssueOps lock trigger. Used for locking branch deployments on a specific branch. Example: "lock"'
    required: false
    default: ".lock"
  unlock_trigger:
    description: 'The string to look for in comments as an IssueOps unlock trigger. Used for unlocking branch deployments. Example: "unlock"'
    required: false
    default: ".unlock"
  reaction:
    description: 'If set, the specified emoji "reaction" is put on the comment to indicate that the trigger was detected. For example, "rocket" or "eyes"'
    required: false
    default: "eyes"
  lock_info_alias:
    description: 'An alias or shortcut to get details about the current lock (if it exists) Example: ".info"'
    required: false
    default: ".wcid"
  prefix_only:
    description: 'If "false", the trigger can match anywhere in the comment'
    required: false
    default: "true"
  mode:
    description: 'The mode to use "lock", "unlock", or "check". If not provided, the default mode assumes the workflow is not headless and triggered by a comment on a pull request - Example: .lock / .unlock'
    required: false
  reason:
    description: Reason for claiming the deployment lock for this repository
    required: false
outputs:
  triggered:
    description: 'The string "true" if the trigger was found, otherwise the string "false"'
  comment_id:
    description: The comment id which triggered this deployment (if it was not headless)
  type:
    description: The type of trigger which was found - 'lock', 'unlock', or 'info-info-alias'
  comment_body:
    description: The comment body which triggered this action (if it was not headless)
  headless:
    description: 'The string "true" if the run was headless, otherwise the string "false" - Headless in this context would be if the "mode" was set and the Action was not invoked by a comment on a pull request'
  locked:
    description: 'If the mode is set to "check", this output will be "true" if a lock exists, otherwise "false"'
  branch:
    description: 'If the mode is set to "check", this output will be the branch name that holds the lock, otherwise it will be empty'
  global_lock_claimed:
    description: 'The string "true" if the global lock was claimed'
  global_lock_released:
    description: 'The string "true" if the global lock was released'
runs:
  using: "node16"
  main: "dist/index.js"
