name: comment-sample

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  contents: write

jobs:
  sample:
    if: ${{ github.event.issue.pull_request }} # only run on pull request comments
    environment: production-secrets
    runs-on: ubuntu-latest
    steps:
      # Need to checkout for testing the Action in this repo
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # pin@v3.0.2

      # Start the branch deployment
      - uses: ./
        id: lock
